/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InspecaoIdRouteImport } from './routes/inspecao.$id'
import { Route as RendimentoIndexRouteImport } from './routes/rendimento.index'
import { Route as AreaIdAreaIdRouteImport } from './routes/area.$id.$areaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspecaoIdRoute = InspecaoIdRouteImport.update({
  id: '/inspecao/$id',
  path: '/inspecao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RendimentoIndexRoute = RendimentoIndexRouteImport.update({
  id: '/rendimento/',
  path: '/rendimento/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaIdAreaIdRoute = AreaIdAreaIdRouteImport.update({
  id: '/area/$id/$areaId',
  path: '/area/$id/$areaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inspecao/$id': typeof InspecaoIdRoute
  '/rendimento/': typeof RendimentoIndexRoute
  '/area/$id/$areaId': typeof AreaIdAreaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inspecao/$id': typeof InspecaoIdRoute
  '/rendimento': typeof RendimentoIndexRoute
  '/area/$id/$areaId': typeof AreaIdAreaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inspecao/$id': typeof InspecaoIdRoute
  '/rendimento/': typeof RendimentoIndexRoute
  '/area/$id/$areaId': typeof AreaIdAreaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inspecao/$id' | '/rendimento/' | '/area/$id/$areaId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inspecao/$id' | '/rendimento' | '/area/$id/$areaId'
  id: '__root__' | '/' | '/inspecao/$id' | '/rendimento/' | '/area/$id/$areaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InspecaoIdRoute: typeof InspecaoIdRoute
  RendimentoIndexRoute: typeof RendimentoIndexRoute
  AreaIdAreaIdRoute: typeof AreaIdAreaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecao/$id': {
      id: '/inspecao/$id'
      path: '/inspecao/$id'
      fullPath: '/inspecao/$id'
      preLoaderRoute: typeof InspecaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendimento/': {
      id: '/rendimento/'
      path: '/rendimento'
      fullPath: '/rendimento/'
      preLoaderRoute: typeof RendimentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area/$id/$areaId': {
      id: '/area/$id/$areaId'
      path: '/area/$id/$areaId'
      fullPath: '/area/$id/$areaId'
      preLoaderRoute: typeof AreaIdAreaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InspecaoIdRoute: InspecaoIdRoute,
  RendimentoIndexRoute: RendimentoIndexRoute,
  AreaIdAreaIdRoute: AreaIdAreaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
